openapi: 3.0.0
info:
  title: New Collection
  version: 1.0.0
servers:
  - url: https://api.restful-api.dev
paths:
  /objects:
    get:
      tags:
        - default
      summary: https://api.restful-api.dev/objects
      parameters:
        - name: accept
          in: header
          schema:
            type: string
          example: >-
            text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
