name: Convert Postman Collection to OpenAPI

on:
  push:
    branches:
      - main  # Cambia 'main' por el nombre de tu rama si es necesario

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Importante para permitir el push de cambios

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install postman-to-openapi
      run: npm install -g postman-to-openapi

    - name: Remove existing OpenAPI file if it exists
      run: |
        if [ -f openapi.yaml ]; then
          rm openapi.yaml
          echo "Existing openapi.yaml removed."
        fi

    - name: Convert Postman collection to OpenAPI
      run: p2o NewCollection.postman_collection.json -f openapi.yaml

    - name: Set up Git credentials using URL
      run: |
        git config --global user.email "jose.sandovalr7@gmail.com"
        git config --global user.name "JoseSandovalR"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/JoseSandovalR/poc-transforms-collection.git
    
    - name: Commit and push if it's necessary
      run: |
        git add openapi.yaml
        git commit -m "Update OpenAPI definition" || exit 0  # El commit fallará si no hay cambios
        git push origin main  # Especifíca la rama, reemplaza 'main' si es necesario
